# pragma: no cover
"""
A collection of data IDs and names for the various Minecraft data tables

"""
import collections

Biome = collections.namedtuple('Biome', 'id', 'name')
Biomes = {
    0: Biome('minecraft:ocean', 'Ocean'),
    1: Biome('minecraft:plains', 'Plains'),
    2: Biome('minecraft:desert', 'Desert'),
    3: Biome('minecraft:mountains', 'Mountains'),
    4: Biome('minecraft:forest', 'Forest'),
    5: Biome('minecraft:taiga', 'Taiga'),
    6: Biome('minecraft:swamp', 'Swamp'),
    7: Biome('minecraft:river', 'River'),
    8: Biome('minecraft:nether', 'Nether'),
    9: Biome('minecraft:the_end', 'The End'),
    10: Biome('minecraft:frozen_ocean', 'Frozen Ocean'),
    11: Biome('minecraft:frozen_river', 'Frozen River'),
    12: Biome('minecraft:snowy_tundra', 'Snowy Tundra'),
    13: Biome('minecraft:snowy_mountains', 'Snowy Mountains'),
    14: Biome('minecraft:mushroom_fields', 'Mushroom Fields'),
    15: Biome('minecraft:mushroom_field_shore', 'Mushroom Field Shore'),
    16: Biome('minecraft:beach', 'Beach'),
    17: Biome('minecraft:desert_hills', 'Desert Hills'),
    18: Biome('minecraft:wooded_hills', 'Wooded Hills'),
    19: Biome('minecraft:taiga_hills', 'Taiga Hills'),
    20: Biome('minecraft:mountain_edge', 'Mountain Edge'),
    21: Biome('minecraft:jungle', 'Jungle'),
    22: Biome('minecraft:jungle_hills', 'Jungle Hills'),
    23: Biome('minecraft:jungle_edge', 'Jungle Edge'),
    24: Biome('minecraft:deep_ocean', 'Deep Ocean'),
    25: Biome('minecraft:stone_shore', 'Stone Shore'),
    26: Biome('minecraft:snowy_beach', 'Snowy Beach'),
    27: Biome('minecraft:birch_forest', 'Birch Forest'),
    28: Biome('minecraft:birch_forest_hills', 'Birch Forest Hills'),
    29: Biome('minecraft:dark_forest', 'Dark Forest'),
    30: Biome('minecraft:snowy_taiga', 'Snowy Taiga'),
    31: Biome('minecraft:snowy_taiga_hills', 'Snowy Taiga Hills'),
    32: Biome('minecraft:giant_tree_taiga', 'Giant Tree Taiga'),
    33: Biome('minecraft:giant_tree_taiga_hills', 'Giant Tree Taiga Hills'),
    34: Biome('minecraft:wooded_mountains', 'Wooded Mountains'),
    35: Biome('minecraft:savanna', 'Savanna'),
    36: Biome('minecraft:savanna_plateau', 'Savanna Plateau'),
    37: Biome('minecraft:badlands', 'Badlands'),
    38: Biome('minecraft:wooded_badlands_plateau', 'Wooded Badlands Plateau'),
    39: Biome('minecraft:badlands_plateau', 'Badlands Plateau'),
    40: Biome('minecraft:small_end_islands', 'Small End Islands'),
    41: Biome('minecraft:end_midlands', 'End Midlands'),
    42: Biome('minecraft:end_highlands', 'End Highlands'),
    43: Biome('minecraft:end_barrens', 'End Barrens'),
    44: Biome('minecraft:warm_ocean', 'Warm Ocean'),
    45: Biome('minecraft:lukewarm_ocean', 'Lukewarm Ocean'),
    46: Biome('minecraft:cold_ocean', 'Cold Ocean'),
    47: Biome('minecraft:deep_warm_ocean', 'Deep Warm Ocean'),
    48: Biome('minecraft:deep_lukewarm_ocean', 'Deep Lukewarm Ocean'),
    49: Biome('minecraft:deep_cold_ocean', 'Deep Cold Ocean'),
    50: Biome('minecraft:deep_frozen_ocean', 'Deep Frozen Ocean'),
    127: Biome('minecraft:the_void', 'The Void'),
    129: Biome('minecraft:sunflower_plains', 'Sunflower Plains'),
    130: Biome('minecraft:desert_lakes', 'Desert Lakes'),
    131: Biome('minecraft:gravelly_mountains', 'Gravelly Mountains'),
    132: Biome('minecraft:flower_forest', 'Flower Forest'),
    133: Biome('minecraft:taiga_mountains', 'Taiga Mountains'),
    134: Biome('minecraft:swamp_hills', 'Swamp Hills'),
    140: Biome('minecraft:ice_spikes', 'Ice Spikes'),
    149: Biome('minecraft:modified_jungle', 'Modified Jungle'),
    151: Biome('minecraft:modified_jungle_edge', 'Modified Jungle Edge'),
    155: Biome('minecraft:tall_birch_forest', 'Tall Birch Forest'),
    156: Biome('minecraft:tall_birch_hills', 'Tall Birch Hills'),
    157: Biome('minecraft:dark_forest_hills', 'Dark Forest Hills'),
    158: Biome('minecraft:snowy_taiga_mountains', 'Snowy Taiga Mountains'),
    160: Biome('minecraft:giant_spruce_taiga', 'Giant Spruce Taiga'),
    161: Biome('minecraft:giant_spruce_taiga_hills',
               'Giant Spruce Taiga Hills'),
    162: Biome('minecraft:modified_gravelly_mountains',
               'Gravelly Mountains+'),
    163: Biome('minecraft:shattered_savanna', 'Shattered Savanna'),
    164: Biome('minecraft:shattered_savanna_plateau',
               'Shattered Savanna Plateau'),
    165: Biome('minecraft:eroded_badlands', 'Eroded Badlands'),
    166: Biome('minecraft:modified_wooded_badlands_plateau',
               'Modified Wooded Badlands Plateau'),
    167: Biome('minecraft:modified_badlands_plateau',
               'Modified Badlands Plateau')
}

Version = collection.namedtuple('Version', 'protocol', 'data', 'release')
Versions = [
    Version('393', '1519', '1.13'),
    Version('340', '1343', '1.12.2'),
    Version('338', '1241', '1.12.1'),
    Version('335', '1139', '1.12'),
]
